private static String url = "jdbc:postgresql://datachan.ctfk86dmi2gc.us-west-1.rds.amazonaws.com:5432/p1reimburs";
    private static String username = "DataChan";
    private static String password = "p4ssw0rd";